import { MOCK_GLITCHES, MOCK_USERS } from './mockData.js';


// When the backend is ready we MUST change this line
const API_BASE = 'http://localhost:8080/api';


// ATTENTION:
// this is the MOCK DATA until the backend isn't ready!
// THEN the fetchGlitches/fetchUsers functions will do the job.
const USE_MOCK = false;
// to be changed to false when backend is ready
// OR adjust we'll need to agree on approach




// API FUNCTIONS
// functions ready to connect to backend
// while not ready we're using mock data.


// Fetches all glitches from backend
// (now it's from mock data - REMOVE THIS COMMENT LATER when Backend connection is done)
// Returns a list of glitch objects.
export async function fetchGlitches() {

    if (USE_MOCK) {
    return MOCK_GLITCHES;
}

const res = await fetch(`${API_BASE}/glitches`);

if (!res.ok) {
    throw new Error('Failed to fetch glitches');
}

const data = await res.json();

return data.map(g => ({
    id: g.id,
    title: g.title,
    description: g.description,

    status: g.glitchStatus,        // IDENTIFIED / BENDING_THE_RULES / SYSTEM_FIXED
    priority: g.glitchPriority,    // GLITCH / HIGH_ALERT / AGENT_SMITH etc

    assignedTo: g.user?.name || 'Unassigned',

    createdAt: g.createdAt,
    resolvedAt: g.resolvedAt
}));
}


// Fetches all users from backend
// (now it's from mock data - REMOVE THIS COMMENT LATER when Backend connection is done)
// Returns a list of user objects.
export async function fetchUsers() {
    if (USE_MOCK) return MOCK_USERS;

    const res = await fetch(`${API_BASE}/users`);

    if (!res.ok) {
    throw new Error('Failed to fetch users');
}

return res.json();
}


// Fetches one glitch by ID from the backend.
// Used by the glitch details page.
export async function fetchGlitchById(id) {
    const res = await fetch(`${API_BASE}/glitches/${id}`);

    if (!res.ok) {
        throw new Error('Failed to fetch glitch details');
    }

    const g = await res.json();

    return {
        id: g.id,
        title: g.title,
        description: g.description,

        status: g.glitchStatus,
        priority: g.glitchPriority,

        assignedTo: g.user?.name || 'Unassigned',
        assignedRole: g.user?.userRole || null,

        createdAt: g.createdAt,
        resolvedAt: g.resolvedAt
    };
}



// Sends a new glitch to the backend
// (now it adds to mock - REMOVE THIS COMMENT LATER when Backend connection is done)
// Automatically assigns a unique ID and default status.
export async function postGlitch(glitchData) {
    if (USE_MOCK) {
    const newGlitch = {
        id: Date.now(),
        ...glitchData,
        status: 'Identified',
    };

    MOCK_GLITCHES.push(newGlitch);

    return newGlitch;
}

const res = await fetch(`${API_BASE}/glitches`, {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
    },
    body: JSON.stringify(glitchData),
});

if (!res.ok) {
    throw new Error('Failed to create glitch');
}

return res.json();
}


// Updates the status of a glitch
// (e.g., Identified → Fixed)
export async function updateGlitchStatus(id, status) {
    if (USE_MOCK) {
    const g = MOCK_GLITCHES.find(g => g.id === id);

    if (g) {
        g.status = status;
    }

    return g;
}


// VERIFICAR IMPORTANTE!!!! NÃO É PUT EM VEZ DE PATCH?? NO CONTROLLER DO UPDATE GLITCH TEMOS "PUT"
const res = await fetch(`${API_BASE}/glitches/${id}/status`, {
    method: 'PATCH',
    headers: {
        'Content-Type': 'application/json',
    },
    body: JSON.stringify({ status }),
});

if (!res.ok) {
    throw new Error('Failed to update status');
}

return res.json();
}

// Marks glitch as resolved.
// resolvedAt function, sets localtimedate and changes status to SYSTEM_FIXED.
export async function resolveGlitch(id) {
    const res = await fetch(`${API_BASE}/glitches/${id}/resolve`, {
        method: 'PUT',
    });

    if (!res.ok) {
        throw new Error('Failed to resolve glitch');
    }

    return res.json();
}


export async function postUser(userData) {
    const res = await fetch(`${API_BASE}/users`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify(userData),
    });

    if (!res.ok) {
        throw new Error('Failed to create user');
    }

    return res.json();
}

export async function deleteUser(id) {
    const res = await fetch(`${API_BASE}/users/${id}`, {
        method: 'DELETE',
    });

    if (!res.ok) {
        throw new Error('Failed to delete user');
    }
}

// Uploads an operative avatar image.
// Returns the image path generated by the backend.
export async function uploadAvatar(file) {
    const formData = new FormData();

    formData.append('file', file);

    const res = await fetch(`${API_BASE}/users/upload-avatar`, {
        method: 'POST',
        body: formData,
    });

    if (!res.ok) {
        throw new Error('Failed to upload avatar');
    }

    return res.text();
}