# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/theglitchtracker

spring.datasource.username=
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# OPENAI
spring.ai.openai.api-key=
spring.ai.openai.chat.model=gpt-4o
spring.ai.openai.embedding.model=text-embedding-3-small
spring.ai.openai.temperature=0.6

# RAG
ai.vector_store_file=/tmp/vector_store.json
ai.rag_number_results=3
ai.rag_documents=
ai.rag_prompt_template=classpath:/ai/templates/rag-prompt-template.st


spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:../../frontend/